services:
    webapp:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5005:8080"
            - "5006:8081"
        networks:
            - webnet
        environment:
            - ACCEPT_EULA=Y
            - ConnectionStrings__DefaultConnection=Server=mysqldb;Port=3306;Database=DieselDatabaseV8;User=root;Password=QwErTy26072026
        depends_on:
            - mysqldb

    mysqldb:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: QwErTy26072026
            MYSQL_DATABASE: DieselDatabaseV8
            MYSQL_USER: diesel
            MYSQL_PASSWORD: JaWelPapa26072026
        ports:
            - "3308:3306"
        volumes:
            - ./DockerData/data:/var/lib/mysql
            - ./DockerData/init:/docker-entrypoint-initdb.d
        networks:
            - webnet

networks:
    webnet: