services:
    mysqldb:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: QwErTy26072026
            MYSQL_DATABASE: DieselDatabaseV8
            MYSQL_USER: diesel
            MYSQL_PASSWORD: JaWelPapa26072026
        ports:
            - "3308:3306"
        volumes:
            - ./data:/var/lib/mysql
            - ./init:/docker-entrypoint-initdb.d